/**
 * torchjs functional tests
 *
 * These tests verify JS outputs match PyTorch's torch.nn.functional exactly.
 * Expected values were generated by running the equivalent PyTorch code.
 *
 * To regenerate expected values:
 *   uv run python3 -c "import torch; import torch.nn.functional as F; ..."
 */

import { describe, it, expect } from 'vitest';
import { nn, tensor } from '../src/index';

// Helper to compare arrays with tolerance
function expectArraysClose(actual: Float32Array | number[], expected: number[], decimals = 5) {
  const actualArr = Array.from(actual);
  expect(actualArr.length).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    expect(actualArr[i]).toBeCloseTo(expected[i], decimals);
  }
}

// ============ Activation Functions ============

describe('activation functions', () => {
  describe('relu', () => {
    it('matches PyTorch output', () => {
      // Python: F.relu(torch.tensor([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0]))
      const input = tensor([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0], [7]);
      const expected = [0.0, 0.0, 0.0, 0.0, 0.5, 1.0, 2.0];

      const result = nn.relu(input);
      expectArraysClose(result.data, expected);
    });
  });

  describe('relu6', () => {
    it('matches PyTorch output', () => {
      // Python: F.relu6(torch.tensor([-1.0, 0.0, 3.0, 6.0, 10.0]))
      const input = tensor([-1.0, 0.0, 3.0, 6.0, 10.0], [5]);
      const expected = [0.0, 0.0, 3.0, 6.0, 6.0];

      const result = nn.relu6(input);
      expectArraysClose(result.data, expected);
    });
  });

  describe('leakyRelu', () => {
    it('matches PyTorch output', () => {
      // Python: F.leaky_relu(torch.tensor([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0]), 0.01)
      const input = tensor([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0], [7]);
      const expected = [-0.02, -0.01, -0.005, 0.0, 0.5, 1.0, 2.0];

      const result = nn.leakyRelu(input, 0.01);
      expectArraysClose(result.data, expected);
    });
  });

  describe('sigmoid', () => {
    it('matches PyTorch output', () => {
      // Python: torch.sigmoid(torch.tensor([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0]))
      const input = tensor([-2.0, -1.0, -0.5, 0.0, 0.5, 1.0, 2.0], [7]);
      const expected = [
        0.11920291930437088,
        0.2689414322376251,
        0.3775406777858734,
        0.5,
        0.622459352016449,
        0.7310585975646973,
        0.8807970285415649,
      ];

      const result = nn.sigmoid(input);
      expectArraysClose(result.data, expected);
    });
  });

  describe('softmax', () => {
    it('matches PyTorch output', () => {
      // Python: F.softmax(torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]), dim=-1)
      const input = tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], [2, 3]);
      const expected = [
        0.09003057330846786, 0.2447284758090973, 0.6652409434318542,
        0.09003057330846786, 0.2447284758090973, 0.6652409434318542,
      ];

      const result = nn.softmax(input, -1);
      expectArraysClose(result.data, expected);
    });
  });

  describe('gelu', () => {
    it('matches PyTorch output approximately', () => {
      // Python: F.gelu(torch.tensor([-1.0, -0.5, 0.0, 0.5, 1.0]))
      const input = tensor([-1.0, -0.5, 0.0, 0.5, 1.0], [5]);
      // GELU uses approximation, allow slightly lower precision
      const expected = [
        -0.15865525603294373,
        -0.15426877141036046,
        0.0,
        0.34573122858963954,
        0.8413447460020364,
      ];

      const result = nn.gelu(input);
      expectArraysClose(result.data, expected, 3); // Lower precision for approximation
    });
  });

  describe('prelu', () => {
    it('matches PyTorch output', () => {
      // Python: F.prelu(torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0]), torch.tensor([0.25]))
      const input = tensor([-2.0, -1.0, 0.0, 1.0, 2.0], [5]);
      const weight = tensor([0.25], [1]);
      const expected = [-0.5, -0.25, 0.0, 1.0, 2.0];

      const result = nn.prelu(input, weight);
      expectArraysClose(result.data, expected);
    });
  });
});

// ============ Convolution Operations ============

describe('convolution operations', () => {
  describe('conv2d', () => {
    it('simple 2x2 kernel, no padding', () => {
      // Python:
      // conv_in = torch.tensor([[[[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]]]])
      // conv_w = torch.tensor([[[[1., 0.], [0., 1.]]]])  # diagonal kernel
      // F.conv2d(conv_in, conv_w)  # [[[[6.0, 8.0], [12.0, 14.0]]]]

      const input = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 1, 3, 3]);
      const weight = tensor([1, 0, 0, 1], [1, 1, 2, 2]);
      const expected = [6.0, 8.0, 12.0, 14.0];

      const result = nn.conv2d(input, weight, null, [1, 1], [0, 0]);
      expect(result.shape).toEqual([1, 1, 2, 2]);
      expectArraysClose(result.data, expected);
    });

    it('with padding', () => {
      // Same input, but with padding=1
      // Output should be 4x4

      const input = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 1, 3, 3]);
      const weight = tensor([1, 0, 0, 1], [1, 1, 2, 2]);

      const result = nn.conv2d(input, weight, null, [1, 1], [1, 1]);
      // With padding, output is (3 + 2*1 - 2)/1 + 1 = 4
      expect(result.shape).toEqual([1, 1, 4, 4]);
    });

    it('with bias', () => {
      // Python:
      // F.conv2d(conv_in, conv_w, bias=torch.tensor([10.]))
      // [[[[16.0, 18.0], [22.0, 24.0]]]]

      const input = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], [1, 1, 3, 3]);
      const weight = tensor([1, 0, 0, 1], [1, 1, 2, 2]);
      const bias = tensor([10], [1]);
      const expected = [16.0, 18.0, 22.0, 24.0];

      const result = nn.conv2d(input, weight, bias, [1, 1], [0, 0]);
      expectArraysClose(result.data, expected);
    });
  });

  describe('depthwiseConv2d', () => {
    it('matches PyTorch groups=channels', () => {
      // Depthwise: each channel gets its own 2x2 filter
      // Input: [1, 2, 4, 4], Weight: [2, 1, 2, 2]

      const input = tensor(
        Array.from({ length: 32 }, (_, i) => i + 1),
        [1, 2, 4, 4]
      );
      const weight = tensor([1, 1, 1, 1, 2, 2, 2, 2], [2, 1, 2, 2]);

      const result = nn.depthwiseConv2d(input, weight, null, [1, 1], [0, 0]);
      expect(result.shape).toEqual([1, 2, 3, 3]);
    });
  });
});

// ============ Pooling Operations ============

describe('pooling operations', () => {
  describe('maxPool2d', () => {
    it('matches PyTorch output', () => {
      // Python:
      // pool_in = torch.tensor([[[[1., 2., 3., 4.], [5., 6., 7., 8.],
      //                           [9., 10., 11., 12.], [13., 14., 15., 16.]]]])
      // F.max_pool2d(pool_in, 2, stride=2)
      // [[[[6.0, 8.0], [14.0, 16.0]]]]

      const input = tensor(
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        [1, 1, 4, 4]
      );
      const expected = [6.0, 8.0, 14.0, 16.0];

      const result = nn.maxPool2d(input, [2, 2], [2, 2], [0, 0]);
      expect(result.shape).toEqual([1, 1, 2, 2]);
      expectArraysClose(result.data, expected);
    });
  });

  describe('avgPool2d', () => {
    it('matches PyTorch output', () => {
      // Python:
      // F.avg_pool2d(pool_in, 2, stride=2)
      // [[[[3.5, 5.5], [11.5, 13.5]]]]

      const input = tensor(
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        [1, 1, 4, 4]
      );
      const expected = [3.5, 5.5, 11.5, 13.5];

      const result = nn.avgPool2d(input, [2, 2], [2, 2], [0, 0]);
      expect(result.shape).toEqual([1, 1, 2, 2]);
      expectArraysClose(result.data, expected);
    });
  });

  describe('globalAvgPool2d', () => {
    it('matches PyTorch adaptive_avg_pool2d', () => {
      // Python:
      // F.adaptive_avg_pool2d(pool_in, (1, 1))
      // [[[[8.5]]]]

      const input = tensor(
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        [1, 1, 4, 4]
      );
      const expected = [8.5];

      const result = nn.globalAvgPool2d(input);
      expect(result.shape).toEqual([1, 1, 1, 1]);
      expectArraysClose(result.data, expected);
    });
  });
});

// ============ Normalization ============

describe('normalization', () => {
  describe('batchNorm', () => {
    it('matches PyTorch inference mode', () => {
      // Simple case: gamma=1, beta=0, mean=0, var=1
      // Output should equal input

      const input = tensor([1, 2, 3, 4], [1, 1, 2, 2]);
      const gamma = tensor([1], [1]);
      const beta = tensor([0], [1]);
      const mean = tensor([0], [1]);
      const variance = tensor([1], [1]);

      const result = nn.batchNorm(input, gamma, beta, mean, variance, 1e-5);
      expectArraysClose(result.data, [1, 2, 3, 4], 4);
    });

    it('applies scale and shift', () => {
      // gamma=2, beta=1, mean=0, var=1
      // Output = (x - 0) / sqrt(1 + eps) * 2 + 1 ≈ 2x + 1

      const input = tensor([0, 1, 2, 3], [1, 1, 2, 2]);
      const gamma = tensor([2], [1]);
      const beta = tensor([1], [1]);
      const mean = tensor([0], [1]);
      const variance = tensor([1], [1]);

      const result = nn.batchNorm(input, gamma, beta, mean, variance, 1e-5);
      // Expected: 2*0+1=1, 2*1+1=3, 2*2+1=5, 2*3+1=7
      expectArraysClose(result.data, [1, 3, 5, 7], 4);
    });
  });
});

// ============ Image Processing ============

describe('image processing', () => {
  describe('resizeBilinear', () => {
    it('upsamples 2x', () => {
      // 2x2 -> 4x4
      const input = tensor([1, 2, 3, 4], [1, 1, 2, 2]);

      const result = nn.resizeBilinear(input, [4, 4]);
      expect(result.shape).toEqual([1, 1, 4, 4]);
      // Just verify it runs and produces correct shape
      expect(result.data.length).toBe(16);
    });

    it('downsamples 2x', () => {
      // 4x4 -> 2x2
      const input = tensor(
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16],
        [1, 1, 4, 4]
      );

      const result = nn.resizeBilinear(input, [2, 2]);
      expect(result.shape).toEqual([1, 1, 2, 2]);
      expect(result.data.length).toBe(4);
    });
  });
});

// ============ Tensor Creation ============

describe('tensor creation', () => {
  it('zeros', async () => {
    const { zeros } = await import('../src/index');
    const t = zeros([2, 3]);
    expect(t.shape).toEqual([2, 3]);
    expect(Array.from(t.data)).toEqual([0, 0, 0, 0, 0, 0]);
  });

  it('ones', async () => {
    const { ones } = await import('../src/index');
    const t = ones([2, 2]);
    expect(t.shape).toEqual([2, 2]);
    expect(Array.from(t.data)).toEqual([1, 1, 1, 1]);
  });
});

// ============ Tensor Manipulation ============

describe('tensor manipulation', () => {
  describe('pad', () => {
    it('pads 2D tensor with constant', () => {
      // Python: F.pad(torch.tensor([[1, 2], [3, 4]]), (1, 1, 1, 1), value=0)
      const input = tensor([1, 2, 3, 4], [1, 1, 2, 2]);
      const result = nn.pad(input, [1, 1, 1, 1], 'constant', 0);
      expect(result.shape).toEqual([1, 1, 4, 4]);
      // Padded with zeros around: 4x4 with 2x2 centered
      const expected = [
        0, 0, 0, 0,
        0, 1, 2, 0,
        0, 3, 4, 0,
        0, 0, 0, 0,
      ];
      expectArraysClose(result.data, expected);
    });

    it('pads asymmetrically', () => {
      const input = tensor([1, 2, 3, 4], [1, 1, 2, 2]);
      const result = nn.pad(input, [0, 1, 0, 1], 'constant', 0); // right=1, bottom=1
      expect(result.shape).toEqual([1, 1, 3, 3]);
      const expected = [
        1, 2, 0,
        3, 4, 0,
        0, 0, 0,
      ];
      expectArraysClose(result.data, expected);
    });
  });

  describe('permute', () => {
    it('transposes 2D tensor', () => {
      // Python: torch.tensor([[1, 2, 3], [4, 5, 6]]).permute(1, 0)
      const input = tensor([1, 2, 3, 4, 5, 6], [2, 3]);
      const result = nn.permute(input, [1, 0]);
      expect(result.shape).toEqual([3, 2]);
      expectArraysClose(result.data, [1, 4, 2, 5, 3, 6]);
    });

    it('permutes NCHW to NHWC', () => {
      // Python: x.permute(0, 2, 3, 1)
      // [1,2,2,2] -> [1,2,2,2] but different order
      const input = tensor([1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 2, 2]);
      const result = nn.permute(input, [0, 2, 3, 1]);
      expect(result.shape).toEqual([1, 2, 2, 2]);
    });
  });

  describe('reshape', () => {
    it('reshapes tensor', () => {
      const input = tensor([1, 2, 3, 4, 5, 6], [2, 3]);
      const result = nn.reshape(input, [3, 2]);
      expect(result.shape).toEqual([3, 2]);
      expectArraysClose(result.data, [1, 2, 3, 4, 5, 6]);
    });

    it('infers -1 dimension', () => {
      const input = tensor([1, 2, 3, 4, 5, 6], [6]);
      const result = nn.reshape(input, [2, -1]);
      expect(result.shape).toEqual([2, 3]);
    });
  });

  describe('squeeze', () => {
    it('removes all size-1 dims', () => {
      const input = tensor([1, 2, 3], [1, 3, 1]);
      const result = nn.squeeze(input);
      expect(result.shape).toEqual([3]);
    });

    it('removes specific dim', () => {
      const input = tensor([1, 2, 3], [1, 3]);
      const result = nn.squeeze(input, 0);
      expect(result.shape).toEqual([3]);
    });
  });

  describe('add', () => {
    it('adds tensors element-wise', () => {
      const a = tensor([1, 2, 3, 4], [2, 2]);
      const b = tensor([10, 20, 30, 40], [2, 2]);
      const result = nn.add(a, b);
      expect(result.shape).toEqual([2, 2]);
      expectArraysClose(result.data, [11, 22, 33, 44]);
    });
  });
});
